### ISSUE TITLE
Testing suggestions!

### ISSUE THREAD

**Issue by sblunt** [vighnesh-nagpal/ecc_distributions#2]
I think the hier_sims code you've written looks pretty good! Here is a first suggestion for a test you could run to check that everything is working correctly. 

Try to reproduce the results from figure 17 of [Bowler+ 2019](https://arxiv.org/pdf/1911.10569.pdf). In particular:

- draw some eccentricities from an assumed underlying beta distribution. Use the same N and sigma as defined in one of the panels of that figure. Plot up all of these distributions on one figure to get a sense of the spread.
- run your hierarchical MCMC to recover the distribution. Plot the recovered MAP distribution and uncertainties as in the figure.
- repeat for different truth values of the underlying beta distribution, and for different N and sigma
- if you're feeling really good, try to perfectly reproduce that entire figure using your own code!

Remember to add this test into the repo itself (perhaps in a "tests" subdirectory)!

**Comment by vighnesh-nagpal** [comment]
Done!
